CREATE PROC usp_ListarUsuarios
AS
	SELECT	P.IDUSER,
			P.USERNAME,
			P.NAME,
			P.LASTNAME,
			P.BIRTH,
			P.PHONE,
			P.EMAIL
	FROM	TM_USER P
GO


CREATE PROC usp_ObtenerUsuario
(
	@IDUSER INT
)
AS
	SELECT	F.IDUSER,
			F.USERNAME,
			F.NAME,
			F.LASTNAME,
			F.BIRTH,
			F.EMAIL
	FROM	TM_USER F
	WHERE	F.IDUSER = @IDUSER
GO


CREATE PROC usp_MostrarEnvios_X_Usuario
(
	@IDUSER INT
)
AS
	SELECT	D.COD_ORDEN,
			D.IDUSER,
			P.NAME AS NOMBRE,
			P.LASTNAME AS APELLIDO,
			D.SRC_ADD,
			D.DEST_ADD,
			D.PRICE,
			D.WEIGHT,
			D.PAQUETE,
			E.NOMBRE_ESTADO
	FROM	TM_ENVIO D
	INNER JOIN TM_USER P ON P.IDUSER = D.IDUSER
	INNER JOIN ESTADO_ENVIO E ON E.COD_ESTADO = D.ESTADO
	WHERE	D.IDUSER = @IDUSER
GO


CREATE PROC usp_Lista_de_envios
AS
	SELECT	D.COD_ORDEN,
			D.IDUSER,
			P.NAME AS NOMBRE,
			P.LASTNAME AS APELLIDO,
			D.SRC_ADD,
			D.DEST_ADD,
			D.PRICE,
			D.WEIGHT,
			D.PAQUETE,
			E.NOMBRE_ESTADO
	FROM	TM_ENVIO D
	INNER JOIN TM_USER P ON P.IDUSER = D.IDUSER
	INNER JOIN ESTADO_ENVIO E ON E.COD_ESTADO = D.ESTADO
GO




/* REGISTRAR USUARIO USERNAME, PASSWORD, NAME, LASTNAME, BIRTH,PHONE, EMAIL */
CREATE PROC usp_Registrar_Usuario
(
	@USERID		INT OUTPUT,
	@USERNAME	VARCHAR(64),
	@PASSWORD	VARCHAR(128),
	@NAME		VARCHAR(256),
	@LASTNAME	VARCHAR(256),
	@BIRTH		DATE,
	@PHONE		VARCHAR(9),
	@EMAIL		VARCHAR(200)
)
AS
	INSERT INTO TM_USER(USERNAME,
						PASSWORD,
						NAME,
						LASTNAME,
						BIRTH,
						PHONE,
						EMAIL) 
	VALUES(	@USERNAME,
			@PASSWORD,
			@NAME,
			@LASTNAME,
			@BIRTH,
			@PHONE,
			@EMAIL)
	SET @USERID = SCOPE_IDENTITY()
GO

/* */


/* REGISTRAR PEDIDO*/
CREATE PROC usp_Registrar_Nuevo_Pedido
(
	@COD_ORDEN 	NCHAR OUTPUT, 
	@IDUSER		INT,
	@SRC_ADD	VARCHAR(64),
	@DEST_ADD	VARCHAR(128),
	@PRICE		DECIMAL,
	@WEIGHT		DECIMAL,
	@PAQUETE	VARCHAR(256)
)
AS
	DECLARE @contador INT
	DECLARE @codorden VARCHAR(15) 
	DECLARE @codi_orden NCHAR	
	SET @contador = (SELECT COUNT(*)+1 FROM TM_ENVIO) 
	SET @codorden = CONCAT('C-000',@contador)
	SET @codi_orden = CONVERT(NCHAR,@codorden)
	
	INSERT INTO TM_ENVIO(COD_ORDEN,
						IDUSER,
						SRC_ADD,
						DEST_ADD,
						PRICE,
						WEIGHT,
						PAQUETE,
						ESTADO) 
	VALUES(	@codorden,
			@IDUSER,
			@SRC_ADD,
			@DEST_ADD,
			@PRICE,
			@WEIGHT,
			@PAQUETE,
			1)
			
	SET @COD_ORDEN = @codi_orden
GO

/* REGISTRAR PEDIDO1*/
CREATE PROC usp_Registrar_Nuevo_Pedido2
(
	@COD_ORDEN INT OUTPUT,
	@IDUSER		INT,
	@SRC_ADD	VARCHAR(64),
	@DEST_ADD	VARCHAR(128),
	@PRICE		DECIMAL,
	@WEIGHT		DECIMAL,
	@PAQUETE	VARCHAR(256)
)
AS
	DECLARE @contador INT
	DECLARE @codorden VARCHAR(15) 
	SET @contador = (SELECT COUNT(*)+1 FROM TM_ENVIO) 
	SET @codorden = CONCAT('C-000',@contador)
	
	INSERT INTO TM_ENVIO(COD_ORDEN,
						IDUSER,
						SRC_ADD,
						DEST_ADD,
						PRICE,
						WEIGHT,
						PAQUETE,
						ESTADO) 
	VALUES(	@codorden,
			@IDUSER,
			@SRC_ADD,
			@DEST_ADD,
			@PRICE,
			@WEIGHT,
			@PAQUETE,
			1)
			
	SET @COD_ORDEN = @contador
GO


/* LOGIN USER*/

CREATE PROC usp_login
(
	@LOGINUSER VARCHAR(64),
	@PASSWORDUSER VARCHAR(128)
)
AS
SELECT	L.IDUSER,
		L.USERNAME,
		L.PASSWORD,
		L.NAME,
		L.LASTNAME,
		L.BIRTH,
		L.PHONE,
		L.EMAIL
FROM	TM_USER L
WHERE	L.USERNAME = @LOGINUSER
		AND L.PASSWORD = @PASSWORDUSER
GO

/* */